import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { ChevronDown, ChevronUp, HelpCircle } from 'lucide-react';

const faqItems = [
  { q: "Is this a job or salary-based position?", a: "No. This is a performance-based Beauty Industry Growth Partner Program. There is no fixed salary or hourly wage." },
  { q: "Is this a franchise or MLM model?", a: "No. Nexora SalonOS is a direct platform growth program focused on genuine business-to-business salon digitalization." },
  { q: "How do I earn?", a: "You earn through two main channels: a One-Time Activation Commission for onboarding genuine shops, and Recurring Growth Share based on the platform revenue they generate." },
  { q: "When do I get payout?", a: "Payouts are processed weekly via direct bank transfer to your linked bank account after verification." },
  { q: "What is an 'active shop'?", a: "An active shop is one that is verified, has its website live on Nexora, and processes genuine customer bookings through the Nexora platform." },
  { q: "What is the One-Time Activation Commission?", a: "A reward paid once after a shop completes 15 active days and generates verified platform revenue." },
  { q: "What is Recurring Growth Share?", a: "A continuous, laddered commission earned as a percentage of Nexora Platform Revenue generated by your onboarded shops over their lifetime." },
  { q: "Can I onboard shops in another district?", a: "Partners are assigned to specific districts to ensure quality support. Onboarding outside your district requires prior approval from Nexora." },
  { q: "Can I withdraw anytime?", a: "Earnings are processed and disbursed on a fixed weekly schedule once minimum threshold requirements are met." },
  { q: "What happens if a shop becomes inactive?", a: "Recurring Growth Share commissions are only applicable for as long as the shop remains active and processes transactions on the platform." },
  { q: "What happens if a transaction is refunded?", a: "Commission is only payable on successful, non-refunded transactions. Refunded or cancelled bookings do not count towards revenue." }
];

export default function GrowthPartnerFAQ() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  return (
    <section className="py-24 bg-slate-50 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto space-y-12">
        <div className="text-center space-y-3">
          <h2 className="text-3xl sm:text-4xl font-black text-slate-900 tracking-tight">Frequently Asked Questions</h2>
          <p className="text-sm text-slate-500 font-semibold">Get answers to critical queries about earnings, partnership, and platform operations.</p>
        </div>

        <div className="space-y-4">
          {faqItems.map((faq, idx) => {
            const isOpen = openFaq === idx;
            return (
              <div key={idx} className="bg-white border border-slate-200/60 rounded-2xl overflow-hidden shadow-sm">
                <button
                  type="button"
                  onClick={() => setOpenFaq(isOpen ? null : idx)}
                  className="w-full text-left p-6 flex justify-between items-center gap-4 hover:bg-slate-50 transition-colors cursor-pointer"
                >
                  <span className="text-sm font-extrabold text-slate-800">{faq.q}</span>
                  {isOpen ? <ChevronUp className="w-5 h-5 text-slate-400" /> : <ChevronDown className="w-5 h-5 text-slate-400" />}
                </button>
                <AnimatePresence>
                  {isOpen && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: 'auto', opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      className="overflow-hidden"
                    >
                      <div className="p-6 border-t border-slate-100 bg-slate-50/50 text-sm text-slate-600 leading-relaxed font-semibold">
                        {faq.a}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
}
